export const REPORT_IMAGE_ANALYSIS_SCHEMA_VERSION = "1.0" as const;
export const MAX_REPORT_IMAGE_ANALYSIS_JSON_LENGTH = 10_000;
export const DEFAULT_REPORT_IMAGE_ANALYSIS_MODEL = "gpt-5.6-terra";

export type ObservationConfidence = "high" | "medium" | "low";

export type ApparentCondition =
  | "appears_alive"
  | "possibly_deceased"
  | "appears_deceased"
  | "unclear";

export interface ImageObservation<T> {
  value: T;
  confidence: ObservationConfidence;
}

export interface ReportImageAnalysis {
  schemaVersion: typeof REPORT_IMAGE_ANALYSIS_SCHEMA_VERSION;
  possibleBirdType: ImageObservation<string | null>;
  estimatedVisibleBirdCount: ImageObservation<number | null>;
  apparentCondition: ImageObservation<ApparentCondition>;
  visibleConcerns: ImageObservation<string[]>;
  environment: ImageObservation<string | null>;
}

export interface ReportImageAnalysisMetadata {
  model: string;
  generatedAt: string;
  schemaVersion: typeof REPORT_IMAGE_ANALYSIS_SCHEMA_VERSION;
}

export interface GeneratedReportImageAnalysis {
  analysis: ReportImageAnalysis;
  metadata: ReportImageAnalysisMetadata;
}

export interface ApprovedImageAnalysis {
  analysis: ReportImageAnalysis;
  model: string;
  schemaVersion: typeof REPORT_IMAGE_ANALYSIS_SCHEMA_VERSION;
  generatedAt: string;
  approvedAt: string;
}

export const REPORT_IMAGE_ANALYSIS_DISCLAIMER =
  "These observations were generated by AI and may be incorrect. They are not a species confirmation, veterinary assessment, or disease diagnosis.";

export const REPORT_IMAGE_ANALYSIS_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "possibleBirdType",
    "estimatedVisibleBirdCount",
    "apparentCondition",
    "visibleConcerns",
    "environment",
  ],
  properties: {
    schemaVersion: { type: "string", enum: ["1.0"] },
    possibleBirdType: observationSchema({
      anyOf: [{ type: "string", minLength: 1, maxLength: 100 }, { type: "null" }],
    }),
    estimatedVisibleBirdCount: observationSchema({
      anyOf: [
        { type: "integer", minimum: 0, maximum: 999 },
        { type: "null" },
      ],
    }),
    apparentCondition: observationSchema({
      type: "string",
      enum: [
        "appears_alive",
        "possibly_deceased",
        "appears_deceased",
        "unclear",
      ],
    }),
    visibleConcerns: observationSchema({
      type: "array",
      minItems: 1,
      maxItems: 5,
      items: { type: "string", minLength: 1, maxLength: 160 },
    }),
    environment: observationSchema({
      anyOf: [{ type: "string", minLength: 1, maxLength: 100 }, { type: "null" }],
    }),
  },
} as const;

function observationSchema(value: object) {
  return {
    type: "object",
    additionalProperties: false,
    required: ["value", "confidence"],
    properties: {
      value,
      confidence: {
        type: "string",
        enum: ["high", "medium", "low"],
      },
    },
  } as const;
}

function isExactRecord(
  value: unknown,
  expectedKeys: ReadonlyArray<string>,
): value is Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return false;
  }

  const keys = Object.keys(value);
  return (
    keys.length === expectedKeys.length &&
    keys.every((key) => expectedKeys.includes(key))
  );
}

function isConfidence(value: unknown): value is ObservationConfidence {
  return value === "high" || value === "medium" || value === "low";
}

function parseObservation<T>(
  value: unknown,
  parseValue: (candidate: unknown) => T | undefined,
): ImageObservation<T> | null {
  if (!isExactRecord(value, ["value", "confidence"])) {
    return null;
  }

  const parsedValue = parseValue(value.value);

  if (parsedValue === undefined || !isConfidence(value.confidence)) {
    return null;
  }

  return { value: parsedValue, confidence: value.confidence };
}

function parseNullableText(value: unknown, maximumLength: number) {
  if (value === null) {
    return null;
  }

  if (typeof value !== "string") {
    return undefined;
  }

  const normalizedValue = value.trim();
  return normalizedValue &&
    normalizedValue.length <= maximumLength &&
    !containsUnsupportedConclusion(normalizedValue)
    ? normalizedValue
    : undefined;
}

function containsUnsupportedConclusion(value: string): boolean {
  return /\b(definit(?:e|ely)|confirm(?:ed|s)?|diagnos(?:e|ed|is)|bird flu|avian influenza|disease detected|died from|cause of death|healthy|uninjured|no injuries|veterinary assessment)\b/i.test(
    value,
  );
}

function parseVisibleCount(value: unknown) {
  return value === null ||
    (Number.isInteger(value) && Number(value) >= 0 && Number(value) <= 999)
    ? (value as number | null)
    : undefined;
}

function parseCondition(value: unknown): ApparentCondition | undefined {
  return value === "appears_alive" ||
    value === "possibly_deceased" ||
    value === "appears_deceased" ||
    value === "unclear"
    ? value
    : undefined;
}

function parseConcerns(value: unknown): string[] | undefined {
  if (!Array.isArray(value) || value.length < 1 || value.length > 5) {
    return undefined;
  }

  const concerns = value.map((concern) =>
    typeof concern === "string" ? concern.trim() : "",
  );

  return concerns.every(
    (concern) =>
      concern.length > 0 &&
      concern.length <= 160 &&
      !containsUnsupportedConclusion(concern),
  )
    ? concerns
    : undefined;
}

export function parseReportImageAnalysis(
  value: unknown,
): ReportImageAnalysis | null {
  if (
    !isExactRecord(value, [
      "schemaVersion",
      "possibleBirdType",
      "estimatedVisibleBirdCount",
      "apparentCondition",
      "visibleConcerns",
      "environment",
    ]) ||
    value.schemaVersion !== REPORT_IMAGE_ANALYSIS_SCHEMA_VERSION
  ) {
    return null;
  }

  const possibleBirdType = parseObservation(value.possibleBirdType, (item) =>
    parseNullableText(item, 100),
  );
  const estimatedVisibleBirdCount = parseObservation(
    value.estimatedVisibleBirdCount,
    parseVisibleCount,
  );
  const apparentCondition = parseObservation(
    value.apparentCondition,
    parseCondition,
  );
  const visibleConcerns = parseObservation(
    value.visibleConcerns,
    parseConcerns,
  );
  const environment = parseObservation(value.environment, (item) =>
    parseNullableText(item, 100),
  );

  if (
    !possibleBirdType ||
    !estimatedVisibleBirdCount ||
    !apparentCondition ||
    !visibleConcerns ||
    !environment
  ) {
    return null;
  }

  return {
    schemaVersion: REPORT_IMAGE_ANALYSIS_SCHEMA_VERSION,
    possibleBirdType,
    estimatedVisibleBirdCount,
    apparentCondition,
    visibleConcerns,
    environment,
  };
}

function isIsoTimestamp(value: unknown): value is string {
  if (typeof value !== "string" || value.length > 40) {
    return false;
  }

  const timestamp = new Date(value);
  return !Number.isNaN(timestamp.getTime()) && timestamp.toISOString() === value;
}

export function parseApprovedImageAnalysis(
  value: unknown,
): ApprovedImageAnalysis | null {
  if (
    !isExactRecord(value, [
      "analysis",
      "model",
      "schemaVersion",
      "generatedAt",
      "approvedAt",
    ]) ||
    typeof value.model !== "string" ||
    !value.model.trim() ||
    value.model.length > 100 ||
    value.schemaVersion !== REPORT_IMAGE_ANALYSIS_SCHEMA_VERSION ||
    !isIsoTimestamp(value.generatedAt) ||
    !isIsoTimestamp(value.approvedAt)
  ) {
    return null;
  }

  const analysis = parseReportImageAnalysis(value.analysis);

  if (!analysis) {
    return null;
  }

  return {
    analysis,
    model: value.model.trim(),
    schemaVersion: REPORT_IMAGE_ANALYSIS_SCHEMA_VERSION,
    generatedAt: value.generatedAt,
    approvedAt: value.approvedAt,
  };
}

export function createApprovedImageAnalysis(
  generated: GeneratedReportImageAnalysis,
  approvedAt: Date = new Date(),
): ApprovedImageAnalysis {
  return {
    analysis: generated.analysis,
    model: generated.metadata.model,
    schemaVersion: REPORT_IMAGE_ANALYSIS_SCHEMA_VERSION,
    generatedAt: generated.metadata.generatedAt,
    approvedAt: approvedAt.toISOString(),
  };
}
